local palette = require 'dimidium.palette'
local util = require 'dimidium.util'

local M = {}

---Build the full highlight table without applying it.
---@param opts DimidiumOpts
---@return table<string, vim.api.keyset.highlight> highlights
---@return DimidiumPalette colors
function M.get(opts)
  local c = vim.deepcopy(palette.colors)
  opts.on_colors(c)

  local st = opts.styles
  local transparent = opts.transparent

  -- Background of "the buffer". NONE when transparent, so every group that
  -- paints the editor surface goes through this instead of hardcoding c.bg.
  local bg = transparent and c.none or c.bg
  local bg_float = transparent and c.none or c.bg_float
  local bg_nc = opts.dim_inactive and c.bg_dim or bg

  ---Merge a base spec with a user style table.
  local function s(base, style)
    return style and next(style) and vim.tbl_extend('force', base, style) or base
  end

  local hl = {
    -- ── Editor surfaces ─────────────────────────────────────────────
    Normal = { fg = c.fg, bg = bg },
    NormalNC = { fg = c.fg, bg = bg_nc },
    NormalFloat = { fg = c.fg, bg = bg_float },
    NormalSB = { fg = c.fg, bg = bg },
    FloatBorder = { fg = c.gray4, bg = bg_float },
    FloatTitle = { fg = c.blue, bg = bg_float, bold = true },
    FloatShadow = { bg = c.bg_dim },
    FloatShadowThrough = { bg = c.none },
    MsgArea = { fg = c.fg },
    MsgSeparator = { fg = c.gray3, bg = bg },

    Cursor = { fg = c.bg, bg = c.fg },
    lCursor = { fg = c.bg, bg = c.fg },
    CursorIM = { fg = c.bg, bg = c.fg },
    TermCursor = { fg = c.bg, bg = c.fg },
    TermCursorNC = { bg = c.gray5 },

    -- gray1 (1.19:1 over bg) sits clearly *below* Visual (1.42:1) so a
    -- selection inside the cursorline is still distinguishable.
    CursorLine = { bg = c.gray1 },
    CursorColumn = { bg = c.gray1 },
    ColorColumn = { bg = c.gray1 },
    CursorLineSign = { bg = c.gray1 },
    CursorLineFold = { fg = c.gray6, bg = c.gray1 },

    -- Blue-tinted but dark: red/blue/magenta keep ~3:1 on top of it, where
    -- the old #3d4450 pushed them down to ~2.1:1.
    Visual = { bg = c.bg_sel },
    VisualNOS = { bg = c.bg_sel },

    Search = { fg = c.bg, bg = c.yellow },
    IncSearch = { fg = c.bg, bg = c.byellow },
    CurSearch = { fg = c.bg, bg = c.bred, bold = true },
    Substitute = { fg = c.bg, bg = c.red },
    MatchParen = { fg = c.byellow, bg = c.gray3, bold = true },

    LineNr = { fg = c.gray5 },
    LineNrAbove = { link = 'LineNr' },
    LineNrBelow = { link = 'LineNr' },
    CursorLineNr = { fg = c.yellow, bold = true },
    SignColumn = { bg = bg },
    FoldColumn = { fg = c.gray5, bg = bg },
    Folded = { fg = c.gray9, bg = c.gray1 },

    NonText = { fg = c.gray4 },
    EndOfBuffer = { fg = c.gray2 },
    SpecialKey = { fg = c.gray4 },
    Whitespace = { fg = c.gray3 },
    Conceal = { fg = c.gray6 },
    Directory = { fg = c.blue },
    Title = { fg = c.blue, bold = true },
    WinSeparator = { fg = c.gray3, bg = bg },
    VertSplit = { link = 'WinSeparator' },

    -- ── Status / tab line ───────────────────────────────────────────
    StatusLine = { fg = c.fg, bg = c.gray1 },
    StatusLineNC = { fg = c.gray6, bg = c.gray1 },
    StatusLineTerm = { link = 'StatusLine' },
    StatusLineTermNC = { link = 'StatusLineNC' },
    TabLine = { fg = c.gray7, bg = c.gray1 },
    TabLineFill = { bg = bg },
    TabLineSel = { fg = c.bg, bg = c.blue, bold = true },
    WinBar = { fg = c.gray9, bg = bg, bold = true },
    WinBarNC = { fg = c.gray6, bg = bg_nc },

    -- ── Messages ────────────────────────────────────────────────────
    ErrorMsg = { fg = c.red, bold = true },
    WarningMsg = { fg = c.yellow, bold = true },
    ModeMsg = { fg = c.fg, bold = true },
    MoreMsg = { fg = c.green, bold = true },
    Question = { fg = c.blue },
    QuickFixLine = { bg = c.bg_sel, bold = true },
    WildMenu = { fg = c.bg, bg = c.blue, bold = true },

    -- ── Popup menu ──────────────────────────────────────────────────
    Pmenu = { fg = c.fg, bg = c.bg_float },
    PmenuSel = { fg = c.fg, bg = c.gray3, bold = true },
    PmenuKind = { fg = c.blue, bg = c.bg_float },
    PmenuKindSel = { fg = c.blue, bg = c.gray3 },
    PmenuExtra = { fg = c.gray6, bg = c.bg_float },
    PmenuExtraSel = { fg = c.gray8, bg = c.gray3 },
    PmenuMatch = { fg = c.byellow, bg = c.bg_float, bold = true },
    PmenuMatchSel = { fg = c.byellow, bg = c.gray3, bold = true },
    PmenuSbar = { bg = c.gray2 },
    PmenuThumb = { bg = c.gray5 },

    -- ── Spell ───────────────────────────────────────────────────────
    SpellBad = { undercurl = true, sp = c.red },
    SpellCap = { undercurl = true, sp = c.yellow },
    SpellLocal = { undercurl = true, sp = c.cyan },
    SpellRare = { undercurl = true, sp = c.magenta },

    -- ── Diff ────────────────────────────────────────────────────────
    DiffAdd = { bg = c.diff_add },
    DiffChange = { bg = c.diff_change },
    DiffDelete = { bg = c.diff_delete },
    DiffText = { bg = c.diff_text },
    -- Generic add/change/delete *text* groups (`:h hl-Added`).
    Added = { fg = c.green },
    Changed = { fg = c.yellow },
    Removed = { fg = c.red },
    diffAdded = { link = 'Added' },
    diffChanged = { link = 'Changed' },
    diffRemoved = { link = 'Removed' },
    diffNewFile = { fg = c.green },
    diffOldFile = { fg = c.red },
    diffFile = { fg = c.blue, bold = true },
    diffLine = { fg = c.gray8 },
    diffIndexLine = { fg = c.magenta },

    -- ── Base syntax ─────────────────────────────────────────────────
    Comment = s({ fg = c.gray8 }, st.comments),
    Constant = { fg = c.magenta },
    String = { fg = c.green },
    Character = { fg = c.green },
    Number = { fg = c.magenta },
    Boolean = s({ fg = c.magenta }, st.booleans),
    Float = { link = 'Number' },
    Identifier = s({ fg = c.blue }, st.variables),
    Function = s({ fg = c.yellow }, st.functions),
    Statement = s({ fg = c.red }, st.keywords),
    Conditional = { link = 'Statement' },
    Repeat = { link = 'Statement' },
    Label = { fg = c.blue },
    Operator = { fg = c.cyan },
    Keyword = { link = 'Statement' },
    Exception = { link = 'Statement' },
    PreProc = { fg = c.cyan },
    Include = { link = 'PreProc' },
    Define = { link = 'PreProc' },
    Macro = { link = 'PreProc' },
    PreCondit = { link = 'PreProc' },
    Type = s({ fg = c.cyan }, st.types),
    StorageClass = { link = 'Statement' },
    Structure = { link = 'Type' },
    Typedef = { link = 'Type' },
    Special = { fg = c.yellow },
    SpecialChar = { fg = c.bred },
    Tag = { fg = c.red },
    Delimiter = { fg = c.gray9 },
    SpecialComment = s({ fg = c.gray9, bold = true }, st.comments),
    Debug = { fg = c.bred },
    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },
    Ignore = { fg = c.gray4 },
    Error = { fg = c.red, bold = true },
    Todo = { fg = c.bg, bg = c.yellow, bold = true },

    -- ── Help / quickfix / builtin filetypes ─────────────────────────
    helpCommand = { fg = c.blue, bg = c.gray1 },
    helpExample = { fg = c.green },
    helpHyperTextJump = { fg = c.blue, underline = true },
    qfFileName = { fg = c.blue },
    qfLineNr = { fg = c.gray8 },
    htmlH1 = { fg = c.magenta, bold = true },
    htmlH2 = { fg = c.blue, bold = true },
    debugPC = { bg = c.diff_change },
    debugBreakpoint = { fg = c.red, bg = c.bg_float },

    -- ── Treesitter ──────────────────────────────────────────────────
    ['@annotation'] = { link = 'PreProc' },
    ['@attribute'] = { link = 'PreProc' },
    ['@attribute.builtin'] = { fg = c.cyan, bold = true },
    ['@boolean'] = { link = 'Boolean' },
    ['@character'] = { link = 'Character' },
    ['@character.special'] = { link = 'SpecialChar' },
    ['@comment'] = { link = 'Comment' },
    ['@comment.error'] = { fg = c.bg, bg = c.red, bold = true },
    ['@comment.warning'] = { fg = c.bg, bg = c.yellow, bold = true },
    ['@comment.todo'] = { fg = c.bg, bg = c.byellow, bold = true },
    ['@comment.note'] = { fg = c.bg, bg = c.cyan, bold = true },
    ['@comment.hint'] = { link = '@comment.note' },
    ['@comment.info'] = { fg = c.bg, bg = c.blue, bold = true },
    ['@constant'] = { link = 'Constant' },
    ['@constant.builtin'] = { fg = c.magenta, bold = true },
    ['@constant.macro'] = { link = 'Define' },
    ['@constructor'] = { fg = c.magenta },
    ['@constructor.lua'] = { fg = c.gray9 },
    ['@diff.delta'] = { link = 'Changed' },
    ['@diff.minus'] = { link = 'Removed' },
    ['@diff.plus'] = { link = 'Added' },
    ['@function'] = { link = 'Function' },
    ['@function.builtin'] = { fg = c.yellow, italic = true },
    ['@function.call'] = { link = '@function' },
    ['@function.macro'] = { link = 'Macro' },
    ['@function.method'] = { link = 'Function' },
    ['@function.method.call'] = { link = '@function.method' },
    ['@keyword'] = { link = 'Keyword' },
    ['@keyword.conditional'] = { link = 'Conditional' },
    ['@keyword.coroutine'] = { link = '@keyword' },
    ['@keyword.debug'] = { link = 'Debug' },
    ['@keyword.directive'] = { link = 'PreProc' },
    ['@keyword.directive.define'] = { link = 'Define' },
    ['@keyword.exception'] = { link = 'Exception' },
    ['@keyword.function'] = { link = '@keyword' },
    ['@keyword.import'] = { link = 'Include' },
    ['@keyword.operator'] = { link = 'Operator' },
    ['@keyword.repeat'] = { link = 'Repeat' },
    ['@keyword.return'] = { link = '@keyword' },
    ['@keyword.storage'] = { link = 'StorageClass' },
    ['@keyword.type'] = { link = '@keyword' },
    ['@label'] = { link = 'Label' },
    ['@markup.emphasis'] = { italic = true },
    ['@markup.environment'] = { link = 'Macro' },
    ['@markup.environment.name'] = { link = 'Type' },
    ['@markup.heading'] = { link = 'Title' },
    ['@markup.heading.1'] = { fg = c.bred, bold = true },
    ['@markup.heading.2'] = { fg = c.byellow, bold = true },
    ['@markup.heading.3'] = { fg = c.bgreen, bold = true },
    ['@markup.heading.4'] = { fg = c.bcyan, bold = true },
    ['@markup.heading.5'] = { fg = c.bblue, bold = true },
    ['@markup.heading.6'] = { fg = c.bmagenta, bold = true },
    ['@markup.italic'] = { italic = true },
    ['@markup.link'] = { fg = c.blue },
    ['@markup.link.label'] = { fg = c.cyan },
    ['@markup.link.url'] = { fg = c.blue, underline = true },
    ['@markup.list'] = { fg = c.cyan },
    ['@markup.list.checked'] = { fg = c.green },
    ['@markup.list.unchecked'] = { fg = c.gray7 },
    ['@markup.math'] = { fg = c.bmagenta },
    ['@markup.quote'] = { fg = c.gray8, italic = true },
    ['@markup.raw'] = { fg = c.green },
    ['@markup.raw.block'] = { bg = c.bg_float },
    ['@markup.strikethrough'] = { strikethrough = true },
    ['@markup.strong'] = { bold = true },
    ['@markup.underline'] = { underline = true },
    ['@module'] = { fg = c.cyan },
    ['@module.builtin'] = { fg = c.cyan, bold = true },
    ['@namespace.builtin'] = { link = '@variable.builtin' },
    ['@none'] = {},
    ['@number'] = { link = 'Number' },
    ['@number.float'] = { link = 'Float' },
    ['@operator'] = { link = 'Operator' },
    ['@property'] = { fg = c.bblue },
    ['@punctuation.bracket'] = { fg = c.gray9 },
    ['@punctuation.delimiter'] = { fg = c.gray9 },
    ['@punctuation.special'] = { fg = c.cyan },
    ['@string'] = { link = 'String' },
    ['@string.documentation'] = { fg = c.green, italic = true },
    ['@string.escape'] = { fg = c.bmagenta, bold = true },
    ['@string.regexp'] = { fg = c.bred },
    ['@string.special'] = { link = 'SpecialChar' },
    ['@string.special.path'] = { fg = c.green, underline = true },
    ['@string.special.symbol'] = { fg = c.magenta },
    ['@string.special.url'] = { fg = c.blue, underline = true },
    ['@tag'] = { fg = c.red },
    ['@tag.attribute'] = { fg = c.bblue, italic = true },
    ['@tag.builtin'] = { fg = c.red, bold = true },
    ['@tag.delimiter'] = { fg = c.gray7 },
    ['@type'] = { link = 'Type' },
    ['@type.builtin'] = s({ fg = c.cyan, italic = true }, st.types),
    ['@type.definition'] = { link = 'Typedef' },
    ['@type.qualifier'] = { link = '@keyword' },
    ['@variable'] = s({ fg = c.fg }, st.variables),
    ['@variable.builtin'] = { fg = c.red, italic = true },
    ['@variable.member'] = { fg = c.bblue },
    ['@variable.parameter'] = { fg = c.bwhite },
    ['@variable.parameter.builtin'] = { fg = c.bwhite, italic = true },

    -- ── LSP semantic tokens ─────────────────────────────────────────
    -- Deliberately empty: let the treesitter capture underneath win.
    ['@lsp.type.variable'] = {},
    ['@lsp.type.boolean'] = { link = '@boolean' },
    ['@lsp.type.builtinType'] = { link = '@type.builtin' },
    ['@lsp.type.class'] = { link = '@type' },
    ['@lsp.type.comment'] = {},
    ['@lsp.type.decorator'] = { link = '@attribute' },
    ['@lsp.type.enum'] = { link = '@type' },
    ['@lsp.type.enumMember'] = { link = '@constant' },
    ['@lsp.type.escapeSequence'] = { link = '@string.escape' },
    ['@lsp.type.formatSpecifier'] = { link = '@markup.list' },
    ['@lsp.type.generic'] = { link = '@variable' },
    ['@lsp.type.interface'] = { fg = c.cyan },
    ['@lsp.type.keyword'] = { link = '@keyword' },
    ['@lsp.type.lifetime'] = { link = '@keyword.storage' },
    ['@lsp.type.namespace'] = { link = '@module' },
    ['@lsp.type.namespace.python'] = { link = '@variable' },
    ['@lsp.type.number'] = { link = '@number' },
    ['@lsp.type.operator'] = { link = '@operator' },
    ['@lsp.type.parameter'] = { link = '@variable.parameter' },
    ['@lsp.type.property'] = { link = '@property' },
    ['@lsp.type.selfKeyword'] = { link = '@variable.builtin' },
    ['@lsp.type.selfTypeKeyword'] = { link = '@variable.builtin' },
    ['@lsp.type.string'] = { link = '@string' },
    ['@lsp.type.struct'] = { link = '@type' },
    ['@lsp.type.typeAlias'] = { link = '@type.definition' },
    ['@lsp.type.typeParameter'] = { link = '@type.definition' },
    ['@lsp.type.unresolvedReference'] = { undercurl = true, sp = c.red },
    ['@lsp.typemod.class.defaultLibrary'] = { link = '@type.builtin' },
    ['@lsp.typemod.enum.defaultLibrary'] = { link = '@type.builtin' },
    ['@lsp.typemod.enumMember.defaultLibrary'] = { link = '@constant.builtin' },
    ['@lsp.typemod.function.builtin'] = { link = '@function.builtin' },
    ['@lsp.typemod.function.defaultLibrary'] = { link = '@function.builtin' },
    ['@lsp.typemod.keyword.async'] = { link = '@keyword.coroutine' },
    ['@lsp.typemod.macro.defaultLibrary'] = { link = '@function.builtin' },
    ['@lsp.typemod.method.defaultLibrary'] = { link = '@function.builtin' },
    ['@lsp.typemod.operator.injected'] = { link = '@operator' },
    ['@lsp.typemod.string.injected'] = { link = '@string' },
    ['@lsp.typemod.struct.defaultLibrary'] = { link = '@type.builtin' },
    ['@lsp.typemod.type.defaultLibrary'] = { link = '@type.builtin' },
    ['@lsp.typemod.typeAlias.defaultLibrary'] = { link = '@type.builtin' },
    ['@lsp.typemod.variable.callable'] = { link = '@function' },
    ['@lsp.typemod.variable.defaultLibrary'] = { link = '@variable.builtin' },
    ['@lsp.typemod.variable.injected'] = { link = '@variable' },
    ['@lsp.typemod.variable.static'] = { link = '@constant' },
    ['@lsp.mod.readonly'] = { link = '@constant' },

    -- ── Diagnostics ─────────────────────────────────────────────────
    DiagnosticError = { fg = c.red },
    DiagnosticWarn = { fg = c.yellow },
    DiagnosticInfo = { fg = c.blue },
    DiagnosticHint = { fg = c.cyan },
    DiagnosticOk = { fg = c.green },
    DiagnosticUnnecessary = { fg = c.gray6, undercurl = true, sp = c.gray6 },
    DiagnosticDeprecated = { strikethrough = true, sp = c.gray6 },
    DiagnosticSignError = { link = 'DiagnosticError' },
    DiagnosticSignWarn = { link = 'DiagnosticWarn' },
    DiagnosticSignInfo = { link = 'DiagnosticInfo' },
    DiagnosticSignHint = { link = 'DiagnosticHint' },
    DiagnosticSignOk = { link = 'DiagnosticOk' },
    DiagnosticFloatingError = { link = 'DiagnosticError' },
    DiagnosticFloatingWarn = { link = 'DiagnosticWarn' },
    DiagnosticFloatingInfo = { link = 'DiagnosticInfo' },
    DiagnosticFloatingHint = { link = 'DiagnosticHint' },
    DiagnosticFloatingOk = { link = 'DiagnosticOk' },
    -- Tinted backgrounds keep virtual text from competing with the code.
    DiagnosticVirtualTextError = { fg = c.red, bg = c.diff_delete },
    DiagnosticVirtualTextWarn = { fg = c.yellow, bg = util.blend(c.yellow, c.bg, 0.13) },
    DiagnosticVirtualTextInfo = { fg = c.blue, bg = c.diff_change },
    DiagnosticVirtualTextHint = { fg = c.cyan, bg = util.blend(c.cyan, c.bg, 0.13) },
    DiagnosticVirtualTextOk = { fg = c.green, bg = c.diff_add },
    DiagnosticUnderlineError = { undercurl = true, sp = c.red },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.yellow },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.blue },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.cyan },
    DiagnosticUnderlineOk = { undercurl = true, sp = c.green },

    -- ── LSP ─────────────────────────────────────────────────────────
    LspReferenceText = { bg = c.gray2 },
    LspReferenceRead = { bg = c.gray2 },
    LspReferenceWrite = { bg = c.gray2, underline = true, sp = c.gray6 },
    LspReferenceTarget = { bg = c.gray2 },
    LspSignatureActiveParameter = { fg = c.byellow, bold = true },
    LspCodeLens = { fg = c.gray6, italic = true },
    LspCodeLensSeparator = { fg = c.gray4 },
    LspInlayHint = { fg = c.gray6, bg = c.gray1, italic = true },
    LspInfoBorder = { link = 'FloatBorder' },
    SnippetTabstop = { bg = c.gray2 },

    -- ── :checkhealth ────────────────────────────────────────────────
    healthError = { fg = c.red },
    healthSuccess = { fg = c.green },
    healthWarning = { fg = c.yellow },
    helpHeader = { fg = c.blue, bold = true },
  }

  -- ── gitsigns.nvim ─────────────────────────────────────────────────
  local git = {
    GitSignsAdd = { fg = c.green },
    GitSignsChange = { fg = c.yellow },
    GitSignsDelete = { fg = c.red },
    GitSignsUntracked = { fg = c.gray6 },
    GitSignsTopdelete = { fg = c.red },
    GitSignsChangedelete = { fg = c.bred },
    GitSignsAddNr = { fg = c.green },
    GitSignsChangeNr = { fg = c.yellow },
    GitSignsDeleteNr = { fg = c.red },
    GitSignsAddLn = { bg = c.diff_add },
    GitSignsChangeLn = { bg = c.diff_change },
    GitSignsDeleteLn = { bg = c.diff_delete },
    GitSignsAddInline = { bg = c.diff_add },
    GitSignsChangeInline = { bg = c.diff_text },
    GitSignsDeleteInline = { bg = c.diff_delete },
    GitSignsAddPreview = { bg = c.diff_add },
    GitSignsDeletePreview = { bg = c.diff_delete },
    GitSignsCurrentLineBlame = { fg = c.gray5, italic = true },
    GitSignsStagedAdd = { fg = c.green, bg = c.gray1 },
    GitSignsStagedChange = { fg = c.yellow, bg = c.gray1 },
    GitSignsStagedDelete = { fg = c.red, bg = c.gray1 },
  }

  -- ── blink.cmp ─────────────────────────────────────────────────────
  local blink = {
    BlinkCmpMenu = { link = 'Pmenu' },
    BlinkCmpMenuBorder = { link = 'FloatBorder' },
    BlinkCmpMenuSelection = { link = 'PmenuSel' },
    BlinkCmpScrollBarGutter = { bg = c.gray1 },
    BlinkCmpScrollBarThumb = { bg = c.gray4 },
    BlinkCmpLabel = { fg = c.fg },
    BlinkCmpLabelDeprecated = { fg = c.gray5, strikethrough = true },
    BlinkCmpLabelMatch = { fg = c.byellow, bold = true },
    BlinkCmpLabelDetail = { fg = c.gray6 },
    BlinkCmpLabelDescription = { fg = c.gray6 },
    BlinkCmpSource = { fg = c.gray5, italic = true },
    BlinkCmpGhostText = { fg = c.gray5, italic = true },
    BlinkCmpDoc = { link = 'NormalFloat' },
    BlinkCmpDocBorder = { link = 'FloatBorder' },
    BlinkCmpDocSeparator = { fg = c.gray3, bg = c.bg_float },
    BlinkCmpDocCursorLine = { bg = c.gray2 },
    BlinkCmpSignatureHelp = { link = 'NormalFloat' },
    BlinkCmpSignatureHelpBorder = { link = 'FloatBorder' },
    BlinkCmpSignatureHelpActiveParameter = { fg = c.byellow, bold = true },
    BlinkCmpKind = { fg = c.blue },
    BlinkCmpKindDefault = { fg = c.gray8 },
  }
  -- Completion kinds share the semantics of the syntax groups above, so drive
  -- them from one table instead of 30 near-identical `set()` calls.
  local kinds = {
    Text = c.green,
    Method = c.yellow,
    Function = c.yellow,
    Constructor = c.magenta,
    Field = c.bblue,
    Variable = c.fg,
    Property = c.bblue,
    Class = c.cyan,
    Interface = c.cyan,
    Struct = c.cyan,
    Enum = c.cyan,
    EnumMember = c.magenta,
    TypeParameter = c.cyan,
    Module = c.blue,
    Namespace = c.blue,
    Package = c.blue,
    Unit = c.green,
    Value = c.magenta,
    Keyword = c.red,
    Snippet = c.bmagenta,
    Color = c.bred,
    File = c.blue,
    Folder = c.blue,
    Reference = c.bred,
    Constant = c.magenta,
    Event = c.bblue,
    Operator = c.cyan,
    Array = c.gray9,
    Boolean = c.magenta,
    Key = c.bblue,
    Null = c.magenta,
    Number = c.magenta,
    Object = c.cyan,
    String = c.green,
    Copilot = c.bcyan,
    Codeium = c.bcyan,
    Supermaven = c.bcyan,
    TabNine = c.bcyan,
  }
  for kind, color in pairs(kinds) do
    blink['BlinkCmpKind' .. kind] = { fg = color }
  end

  -- ── snacks.nvim ───────────────────────────────────────────────────
  local snacks = {
    SnacksNormal = { link = 'NormalFloat' },
    SnacksNormalNC = { link = 'NormalFloat' },
    SnacksWinBar = { link = 'Title' },
    SnacksWinBarNC = { link = 'SnacksWinBar' },
    SnacksBackdrop = { bg = c.bg },
    SnacksScratchTitle = { fg = c.bg, bg = c.green, bold = true },
    SnacksScratchDesc = { fg = c.gray8 },
    SnacksScratchKey = { fg = c.byellow },
    -- notifier
    SnacksNotifierInfo = { fg = c.fg },
    SnacksNotifierIconInfo = { fg = c.blue },
    SnacksNotifierTitleInfo = { fg = c.blue, italic = true },
    SnacksNotifierBorderInfo = { fg = c.blue, bg = c.bg_float },
    SnacksNotifierFooterInfo = { link = 'DiagnosticInfo' },
    SnacksNotifierWarn = { fg = c.fg },
    SnacksNotifierIconWarn = { fg = c.yellow },
    SnacksNotifierTitleWarn = { fg = c.yellow, italic = true },
    SnacksNotifierBorderWarn = { fg = c.yellow, bg = c.bg_float },
    SnacksNotifierFooterWarn = { link = 'DiagnosticWarn' },
    SnacksNotifierError = { fg = c.fg },
    SnacksNotifierIconError = { fg = c.red },
    SnacksNotifierTitleError = { fg = c.red, italic = true },
    SnacksNotifierBorderError = { fg = c.red, bg = c.bg_float },
    SnacksNotifierFooterError = { link = 'DiagnosticError' },
    SnacksNotifierDebug = { fg = c.fg },
    SnacksNotifierIconDebug = { fg = c.magenta },
    SnacksNotifierTitleDebug = { fg = c.magenta, italic = true },
    SnacksNotifierBorderDebug = { fg = c.magenta, bg = c.bg_float },
    SnacksNotifierFooterDebug = { fg = c.magenta },
    SnacksNotifierTrace = { fg = c.fg },
    SnacksNotifierIconTrace = { fg = c.gray8 },
    SnacksNotifierTitleTrace = { fg = c.gray8, italic = true },
    SnacksNotifierBorderTrace = { fg = c.gray6, bg = c.bg_float },
    SnacksNotifierFooterTrace = { fg = c.gray8 },
    SnacksNotifierHistoryDateTime = { fg = c.gray6 },
    SnacksNotifierHistoryTitle = { fg = c.blue, bold = true },
    -- dashboard
    SnacksDashboardNormal = { link = 'Normal' },
    SnacksDashboardDesc = { fg = c.blue },
    SnacksDashboardFile = { fg = c.bblue },
    SnacksDashboardDir = { fg = c.gray6 },
    SnacksDashboardFooter = { fg = c.gray6, italic = true },
    SnacksDashboardHeader = { fg = c.bblue },
    SnacksDashboardIcon = { fg = c.bgreen, bold = true },
    SnacksDashboardKey = { fg = c.byellow },
    SnacksDashboardSpecial = { link = 'Special' },
    SnacksDashboardTitle = { link = 'Title' },
    SnacksDashboardTerminal = { link = 'Normal' },
    -- indent
    SnacksIndent = { fg = c.gray2 },
    SnacksIndentScope = { fg = c.gray5 },
    SnacksIndentChunk = { fg = c.gray5 },
    SnacksIndentBlank = { fg = c.gray2 },
    -- picker
    SnacksPicker = { link = 'NormalFloat' },
    SnacksPickerBorder = { link = 'FloatBorder' },
    SnacksPickerTitle = { fg = c.bg, bg = c.magenta, bold = true },
    SnacksPickerInput = { link = 'NormalFloat' },
    SnacksPickerInputBorder = { fg = c.yellow, bg = c.bg_float },
    SnacksPickerInputTitle = { fg = c.bg, bg = c.yellow, bold = true },
    SnacksPickerInputSearch = { fg = c.byellow },
    SnacksPickerList = { link = 'NormalFloat' },
    SnacksPickerListTitle = { fg = c.bg, bg = c.blue, bold = true },
    SnacksPickerPreview = { link = 'NormalFloat' },
    SnacksPickerPreviewTitle = { fg = c.bg, bg = c.green, bold = true },
    SnacksPickerBoxTitle = { fg = c.bg, bg = c.blue, bold = true },
    SnacksPickerPrompt = { fg = c.yellow },
    SnacksPickerMatch = { fg = c.byellow, bold = true },
    SnacksPickerSelected = { fg = c.bred },
    SnacksPickerCursorLine = { bg = c.gray2 },
    SnacksPickerToggle = { fg = c.gray8, bg = c.gray2 },
    SnacksPickerDir = { fg = c.gray6 },
    SnacksPickerFile = { fg = c.fg },
    SnacksPickerDirectory = { fg = c.blue },
    SnacksPickerIdx = { fg = c.gray6 },
    SnacksPickerRow = { fg = c.gray6 },
    SnacksPickerCol = { fg = c.gray5 },
    SnacksPickerDelim = { fg = c.gray5 },
    SnacksPickerComment = { fg = c.gray8, italic = true },
    SnacksPickerLabel = { fg = c.magenta },
    SnacksPickerKeymapRhs = { fg = c.gray6 },
    SnacksPickerBufFlags = { fg = c.gray6 },
    SnacksPickerCode = { fg = c.cyan },
    SnacksPickerAdded = { link = 'Added' },
    SnacksPickerChanged = { link = 'Changed' },
    SnacksPickerRemoved = { link = 'Removed' },
    SnacksPickerGitStatusUntracked = { fg = c.gray6 },
    SnacksPickerGitStatusModified = { fg = c.yellow },
    SnacksPickerGitStatusAdded = { fg = c.green },
    SnacksPickerGitStatusDeleted = { fg = c.red },
    SnacksPickerGitStatusRenamed = { fg = c.blue },
    SnacksPickerGitBranch = { fg = c.magenta },
    SnacksPickerPickWin = { fg = c.fg, bg = c.gray3, bold = true },
    SnacksPickerPickWinCurrent = { fg = c.bg, bg = c.bblue, bold = true },
    -- misc
    SnacksInputIcon = { fg = c.blue },
    SnacksInputBorder = { fg = c.yellow, bg = c.bg_float },
    SnacksInputTitle = { fg = c.bg, bg = c.yellow, bold = true },
    SnacksZenIcon = { fg = c.magenta },
    SnacksProfilerIconInfo = { fg = c.blue, bg = c.gray2 },
    SnacksProfilerBadgeInfo = { fg = c.blue, bg = c.gray1 },
    SnacksProfilerIconTrace = { fg = c.gray8, bg = c.gray2 },
    SnacksProfilerBadgeTrace = { fg = c.gray7, bg = c.gray1 },
    SnacksFooterKey = { fg = c.blue, bg = c.gray2 },
    SnacksFooterDesc = { fg = c.gray8, bg = c.gray1 },
    SnacksGhLabel = { fg = c.bblue, bold = true },
    SnacksGhDiffHeader = { fg = c.blue, bg = c.gray1 },
    SnacksStatusColumnMark = { fg = c.magenta },
  }
  local rainbow = { c.red, c.yellow, c.green, c.cyan, c.blue, c.magenta, c.bred, c.byellow }
  for i, color in ipairs(rainbow) do
    snacks['SnacksIndent' .. i] = { fg = color }
  end

  -- ── oil.nvim ──────────────────────────────────────────────────────
  local oil = {
    OilDir = { fg = c.blue, bold = true },
    OilDirIcon = { fg = c.blue },
    OilFile = { fg = c.fg },
    OilLink = { fg = c.cyan },
    OilLinkTarget = { fg = c.cyan, italic = true },
    OilSocket = { fg = c.magenta },
    OilHidden = { fg = c.gray6 },
    OilSize = { fg = c.magenta },
    OilMtime = { fg = c.gray7 },
    OilCreate = { fg = c.green },
    OilDelete = { fg = c.red },
    OilMove = { fg = c.yellow },
    OilCopy = { fg = c.cyan },
    OilChange = { fg = c.yellow },
    OilRestore = { fg = c.green },
    OilPurge = { fg = c.bred },
    OilTrash = { fg = c.red },
    OilTrashSourcePath = { fg = c.gray6 },
    OilPermissionNone = { fg = c.gray5 },
    OilPermissionRead = { fg = c.yellow },
    OilPermissionWrite = { fg = c.red },
    OilPermissionExecute = { fg = c.green },
    OilTypeDir = { fg = c.blue },
    OilTypeFile = { fg = c.gray7 },
    OilTypeLink = { fg = c.cyan },
    OilTypeSocket = { fg = c.magenta },
    OilTypeFifo = { fg = c.magenta },
    OilTypeSpecial = { fg = c.bred },
  }

  -- ── todo-comments.nvim ────────────────────────────────────────────
  local todo = {}
  local todo_kinds = {
    FIX = c.red,
    TODO = c.blue,
    HACK = c.yellow,
    WARN = c.yellow,
    PERF = c.magenta,
    NOTE = c.green,
    TEST = c.cyan,
  }
  for kind, color in pairs(todo_kinds) do
    todo['TodoFg' .. kind] = { fg = color }
    todo['TodoBg' .. kind] = { fg = c.bg, bg = color, bold = true }
    todo['TodoSign' .. kind] = { fg = color }
  end

  -- ── indent-blankline.nvim ─────────────────────────────────────────
  local ibl = {
    IblIndent = { fg = c.gray2 },
    IblWhitespace = { fg = c.gray2 },
    IblScope = { fg = c.gray5 },
  }

  -- ── which-key.nvim ────────────────────────────────────────────────
  local whichkey = {
    WhichKey = { fg = c.cyan, bold = true },
    WhichKeyGroup = { fg = c.blue },
    WhichKeyDesc = { fg = c.fg },
    WhichKeySeparator = { fg = c.gray5 },
    WhichKeyValue = { fg = c.gray7 },
    WhichKeyIcon = { fg = c.magenta },
    WhichKeyNormal = { link = 'NormalFloat' },
    WhichKeyBorder = { link = 'FloatBorder' },
    WhichKeyTitle = { fg = c.bg, bg = c.blue, bold = true },
  }

  -- ── nvim-dap / nvim-dap-ui ────────────────────────────────────────
  local dap = {
    DapBreakpoint = { fg = c.red },
    DapBreakpointCondition = { fg = c.yellow },
    DapBreakpointRejected = { fg = c.gray6 },
    DapLogPoint = { fg = c.cyan },
    DapStopped = { fg = c.bgreen },
    DapStoppedLine = { bg = c.diff_change },
    DapUINormal = { link = 'NormalFloat' },
    DapUIFloatBorder = { link = 'FloatBorder' },
    DapUIEndofBuffer = { fg = c.gray2 },
    DapUIVariable = { fg = c.fg },
    DapUIScope = { fg = c.cyan },
    DapUIType = { fg = c.magenta },
    DapUIValue = { fg = c.fg },
    DapUIModifiedValue = { fg = c.byellow, bold = true },
    DapUIDecoration = { fg = c.gray5 },
    DapUIThread = { fg = c.green },
    DapUIStoppedThread = { fg = c.bgreen },
    DapUISource = { fg = c.blue },
    DapUILineNumber = { fg = c.gray6 },
    DapUIFrameName = { fg = c.fg },
    DapUIBreakpointsPath = { fg = c.blue },
    DapUIBreakpointsInfo = { fg = c.cyan },
    DapUIBreakpointsCurrentLine = { fg = c.byellow, bold = true },
    DapUIBreakpointsLine = { fg = c.gray6 },
    DapUIBreakpointsDisabledLine = { fg = c.gray5 },
    DapUIWatchesEmpty = { fg = c.gray6 },
    DapUIWatchesValue = { fg = c.green },
    DapUIWatchesError = { fg = c.red },
    DapUIPlayPause = { fg = c.green },
    DapUIRestart = { fg = c.bgreen },
    DapUIStop = { fg = c.red },
    DapUIUnavailable = { fg = c.gray5 },
    DapUIStepOver = { fg = c.blue },
    DapUIStepInto = { fg = c.blue },
    DapUIStepBack = { fg = c.blue },
    DapUIStepOut = { fg = c.blue },
    DapUIWinSelect = { fg = c.byellow, bold = true },
  }

  -- ── render-markdown.nvim ──────────────────────────────────────────
  local rm = {
    RenderMarkdownCode = { bg = c.bg_float },
    RenderMarkdownCodeInline = { fg = c.green, bg = c.gray1 },
    RenderMarkdownBullet = { fg = c.cyan },
    RenderMarkdownDash = { fg = c.gray4 },
    RenderMarkdownQuote = { fg = c.gray6 },
    RenderMarkdownLink = { fg = c.blue, underline = true },
    RenderMarkdownMath = { fg = c.bmagenta },
    RenderMarkdownTableHead = { fg = c.magenta },
    RenderMarkdownTableRow = { fg = c.gray8 },
    RenderMarkdownTableFill = { link = 'Conceal' },
    RenderMarkdownSuccess = { fg = c.green },
    RenderMarkdownInfo = { fg = c.blue },
    RenderMarkdownHint = { fg = c.cyan },
    RenderMarkdownWarn = { fg = c.yellow },
    RenderMarkdownError = { fg = c.red },
    RenderMarkdownUnchecked = { fg = c.gray7 },
    RenderMarkdownChecked = { fg = c.green },
    RenderMarkdownTodo = { fg = c.yellow },
  }
  local headings = { c.bred, c.byellow, c.bgreen, c.bcyan, c.bblue, c.bmagenta }
  for i, color in ipairs(headings) do
    rm['RenderMarkdownH' .. i] = { fg = color, bold = true }
    rm['RenderMarkdownH' .. i .. 'Bg'] = { fg = color, bg = util.blend(color, c.bg, 0.12) }
  end

  -- ── mini.nvim ─────────────────────────────────────────────────────
  local mini = {
    MiniIndentscopeSymbol = { fg = c.gray5 },
    MiniIndentscopeSymbolOff = { fg = c.gray3 },
    MiniSurround = { fg = c.bg, bg = c.byellow },
    MiniTrailspace = { bg = c.red },
    MiniStarterCurrent = { bold = true },
    MiniStarterFooter = { fg = c.gray6, italic = true },
    MiniStarterHeader = { fg = c.bblue },
    MiniStarterInactive = { fg = c.gray6 },
    MiniStarterItem = { link = 'Normal' },
    MiniStarterItemBullet = { fg = c.gray6 },
    MiniStarterItemPrefix = { fg = c.yellow },
    MiniStarterSection = { fg = c.blue, bold = true },
    MiniStarterQuery = { fg = c.byellow, bold = true },
    MiniStatuslineDevinfo = { fg = c.gray8, bg = c.gray1 },
    MiniStatuslineFileinfo = { fg = c.gray8, bg = c.gray1 },
    MiniStatuslineFilename = { fg = c.fg, bg = c.gray2 },
    MiniStatuslineInactive = { fg = c.gray6, bg = c.gray1 },
    MiniStatuslineModeNormal = { fg = c.bg, bg = c.blue, bold = true },
    MiniStatuslineModeInsert = { fg = c.bg, bg = c.green, bold = true },
    MiniStatuslineModeVisual = { fg = c.bg, bg = c.magenta, bold = true },
    MiniStatuslineModeReplace = { fg = c.bg, bg = c.red, bold = true },
    MiniStatuslineModeCommand = { fg = c.bg, bg = c.yellow, bold = true },
    MiniStatuslineModeOther = { fg = c.bg, bg = c.cyan, bold = true },
    -- mini.icons (used by oil.nvim for filetype icons)
    MiniIconsAzure = { fg = c.bblue },
    MiniIconsBlue = { fg = c.blue },
    MiniIconsCyan = { fg = c.cyan },
    MiniIconsGreen = { fg = c.green },
    MiniIconsGrey = { fg = c.gray8 },
    MiniIconsOrange = { fg = c.bred },
    MiniIconsPurple = { fg = c.magenta },
    MiniIconsRed = { fg = c.red },
    MiniIconsYellow = { fg = c.yellow },
  }

  -- ── nvim-notify ───────────────────────────────────────────────────
  local notify = { NotifyBackground = { bg = c.bg_float } }
  local levels = {
    ERROR = c.red,
    WARN = c.yellow,
    INFO = c.blue,
    DEBUG = c.magenta,
    TRACE = c.gray8,
  }
  for level, color in pairs(levels) do
    notify['Notify' .. level .. 'Border'] = { fg = color, bg = c.bg_float }
    notify['Notify' .. level .. 'Icon'] = { fg = color }
    notify['Notify' .. level .. 'Title'] = { fg = color, bold = true }
    notify['Notify' .. level .. 'Body'] = { link = 'NormalFloat' }
  end

  -- ── telescope.nvim ────────────────────────────────────────────────
  local telescope = {
    TelescopeNormal = { link = 'NormalFloat' },
    TelescopeBorder = { link = 'FloatBorder' },
    TelescopePromptNormal = { link = 'NormalFloat' },
    TelescopePromptBorder = { fg = c.yellow, bg = c.bg_float },
    TelescopePromptTitle = { fg = c.bg, bg = c.yellow, bold = true },
    TelescopePromptPrefix = { fg = c.yellow },
    TelescopeResultsBorder = { link = 'FloatBorder' },
    TelescopeResultsTitle = { fg = c.bg, bg = c.blue, bold = true },
    TelescopePreviewBorder = { link = 'FloatBorder' },
    TelescopePreviewTitle = { fg = c.bg, bg = c.green, bold = true },
    TelescopeSelection = { bg = c.gray2, bold = true },
    TelescopeSelectionCaret = { fg = c.bred, bg = c.gray2 },
    TelescopeMatching = { fg = c.byellow, bold = true },
  }

  -- ── lazy.nvim / mason.nvim / treesitter-context ───────────────────
  local tooling = {
    LazyNormal = { link = 'NormalFloat' },
    LazyH1 = { fg = c.bg, bg = c.blue, bold = true },
    LazyH2 = { fg = c.blue, bold = true },
    LazyButton = { fg = c.gray8, bg = c.gray1 },
    LazyButtonActive = { fg = c.bg, bg = c.blue, bold = true },
    LazySpecial = { fg = c.cyan },
    LazyProp = { fg = c.gray7 },
    LazyDimmed = { fg = c.gray6 },
    LazyCommit = { fg = c.magenta },
    LazyCommitIssue = { fg = c.bred },
    LazyProgressDone = { fg = c.green, bold = true },
    LazyProgressTodo = { fg = c.gray3, bold = true },
    LazyReasonPlugin = { fg = c.magenta },
    LazyReasonRuntime = { fg = c.bmagenta },
    LazyReasonCmd = { fg = c.yellow },
    LazyReasonEvent = { fg = c.bblue },
    LazyReasonFt = { fg = c.blue },
    LazyReasonKeys = { fg = c.cyan },
    LazyReasonStart = { fg = c.bgreen },
    LazyReasonSource = { fg = c.green },
    LazyReasonImport = { fg = c.fg },
    LazyReasonRequire = { fg = c.bcyan },

    MasonNormal = { link = 'NormalFloat' },
    MasonHeader = { fg = c.bg, bg = c.blue, bold = true },
    MasonHeaderSecondary = { fg = c.bg, bg = c.magenta, bold = true },
    MasonHighlight = { fg = c.blue },
    MasonHighlightBlock = { fg = c.bg, bg = c.blue },
    MasonHighlightBlockBold = { fg = c.bg, bg = c.blue, bold = true },
    MasonMuted = { fg = c.gray6 },
    MasonMutedBlock = { fg = c.gray8, bg = c.gray1 },
    MasonMutedBlockBold = { fg = c.gray8, bg = c.gray1, bold = true },
    MasonError = { fg = c.red },

    TreesitterContext = { bg = c.gray1 },
    TreesitterContextLineNumber = { fg = c.gray5, bg = c.gray1 },
    TreesitterContextBottom = { underline = true, sp = c.gray3 },
    TreesitterContextSeparator = { fg = c.gray3 },
  }

  for _, group in ipairs { git, blink, snacks, oil, todo, ibl, whichkey, dap, rm, mini, notify, telescope, tooling } do
    for name, spec in pairs(group) do
      hl[name] = spec
    end
  end

  opts.on_highlights(hl, c)
  return hl, c
end

return M
